static:
  # Домены
  play_domain: "ʀᴇᴅᴍᴄ.ɢɢ"  # %design_play_domain%
  store_domain: "ʀᴇᴅᴍᴄ.ʀᴜ"  # %design_store_domain%
  store_url: "https://redmc.ru/store"  # %design_store_url%
  store_url_display: "ʀᴇᴅᴍᴄ.ʀᴜ/sᴛᴏʀᴇ"  # %design_store_url_display%
  store_url_simple: "www.redmc.ru"    #%design_store_url_simple%

  # Ссылки
  telegram_channel_url: "https://t.me/redmc_gg"  # %design_telegram_channel_url%
  telegram_channel_url_display: "ᴛ.ᴍᴇ/ʀᴇᴅᴍᴄ_ɢɢ"  # %design_telegram_channel_url_display%

  telegram_support_url: "https://t.me/redmc_support_bot"  # %design_telegram_support_url%
  telegram_support_url_display: "ᴛ.ᴍᴇ/ʀᴇᴅᴍᴄ_sᴜᴘᴘᴏʀᴛ_ʙᴏᴛ"  # %design_telegram_support_url_display%

  vk_public_url: "https://vk.com/redmc_gg"  # %design_vk_public_url%
  vk_public_url_display: "ᴠᴋ.ᴄᴏᴍ/ʀᴇᴅᴍᴄ_ɢɢ"  # %design_vk_public_url_display%

  discord_server_url: "https://discord.gg/redmc_gg"  # %design_discord_server_url%
  discord_server_url_display: "ᴅɪsᴄᴏʀᴅ.ɢɢ/ʀᴇᴅᴍᴄ_ɢɢ"  # %design_discord_server_url_display%

  # Цвета
  clr_primary: "&#FF0048"  # %design_clr_primary%
  clr_secondary: "&#FF0048"  # %design_clr_secondary%

  clr_text_primary: "&#CFCFCF"  # %design_clr_text_primary%
  clr_text_secondary: "&7"  # %design_clr_text_secondary%
  clr_text_dark: "&8"  # %design_clr_text_dark%

  clr_money: "&#BBD884"  # %design_clr_money%
  clr_sapphire: "&#68C6D7"  # %design_clr_sapphire%

  # Ранги
  clr_copper: "&#ee8b6f"  # %design_clr_copper%
  clr_gold: "&#eccc8b"  # %design_clr_gold%
  clr_diamond: "&#65c7d2"  # %design_clr_diamond%
  clr_emerald: "&#8cd742"  # %design_clr_emerald%
  clr_amethyst: "&#c08cd4"  # %design_clr_amethyst%
  clr_ruby: "&#AA0D55"  # %design_clr_ruby%

  # Предметы. Пока что ссылаются на основные цвета (bad practice, лучше захардкодить в ручную). ps. на будущее сделать парсинг и определенный формат.
  i_title: "%design_clr_primary%"  # %design_i_title%
  i_lore: "%design_clr_text_primary%"
  i_extra: ""

playerformat:
  default_icon: ""                                                                                      #   %pFormat_MrDarkiMC_icon%
  default_prefix: "&f%img_default% &#8F8F8F"                                                            #   %pFormat_MrDarkiMC_prefix%
  default_format: "&f &#8F8F8F{nickname}%luckperms_suffix%"                                           #   %pFormat_MrDarkiMC_format%
  default_full: "&f %img_default% &#8F8F8F{nickname}%luckperms_suffix%"                               #   %pFormat_MrDarkiMC_full%

  copper_icon: ""                                                                                      #   %pFormat_MrDarkiMC_icon%
  copper_prefix: "&f%img_copper% &#F48C6C"                                                             #   %pFormat_MrDarkiMC_prefix%
  copper_format: "  &#F48C6C{nickname}%luckperms_suffix%"                                             #   %pFormat_MrDarkiMC_format%
  copper_full: "&f %img_copper% &#F48C6C{nickname}%luckperms_suffix%"                                #   %pFormat_MrDarkiMC_full%

  gold_icon: ""                                                                                        #   %pFormat_MrDarkiMC_icon%
  gold_prefix: "&f%img_gold% &#E5B74D"                                                                 #   %pFormat_MrDarkiMC_prefix%
  gold_format: "&f &#E5B74D{nickname}%luckperms_suffix%"                                             #   %pFormat_MrDarkiMC_format%
  gold_full: "&f %img_gold% &#E5B74D{nickname}%luckperms_suffix%"                                    #   %pFormat_MrDarkiMC_full%

  diamond_icon: ""                                                                                     #   %pFormat_MrDarkiMC_icon%
  diamond_prefix: "&f%img_diamond% &#04BCCC"                                                           #   %pFormat_MrDarkiMC_prefix%
  diamond_format: "&f &#04BCCC{nickname}%luckperms_suffix%"                                          #   %pFormat_MrDarkiMC_format%
  diamond_full: "&f %img_diamond% &#04BCCC{nickname}%luckperms_suffix%"                              #   %pFormat_MrDarkiMC_full%

  emerald_icon: ""                                                                                     #   %pFormat_MrDarkiMC_icon%
  emerald_prefix: "&f%img_emerald% &#94E61D"                                                           #   %pFormat_MrDarkiMC_prefix%
  emerald_format: "&f &#94E61D{nickname}%luckperms_suffix%"                                          #   %pFormat_MrDarkiMC_format%
  emerald_full: "&f %img_emerald% &#94E61D{nickname}%luckperms_suffix%"                              #   %pFormat_MrDarkiMC_full%

  amethyst_icon: ""                                                                                    #   %pFormat_MrDarkiMC_icon%
  amethyst_prefix: "&f%img_amethyst% &#AC74C4"                                                         #   %pFormat_MrDarkiMC_prefix%
  amethyst_format: "&f &#AC74C4{nickname}%luckperms_suffix%"                                         #   %pFormat_MrDarkiMC_format%
  amethyst_full: "&f %img_amethyst% &#AC74C4{nickname}%luckperms_suffix%"                            #   %pFormat_MrDarkiMC_full%

  ruby_icon: ""                                                                                        #   %pFormat_MrDarkiMC_icon%
  ruby_prefix: "&f%img_ruby% &#881856"                                                                 #   %pFormat_MrDarkiMC_prefix%
  ruby_format: "&f &#881856{nickname}%luckperms_suffix%"                                             #   %pFormat_MrDarkiMC_format%
  ruby_full: "&f %img_ruby% &#881856{nickname}%luckperms_suffix%"                                    #   %pFormat_MrDarkiMC_full%
modules:
  bossbar:
    enable: true
    update: 50
    enable_second_layer: true
    titles:
      default: "&f%img_default% &#8F8F8F{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      copper: "&f%img_copper% &#F48C6C{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      gold: "&f%img_gold% &#E5B74D{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      diamond: "&f%img_diamond% &#04BCCC &#8F8F8F{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      emerald: "&f%img_emerald% &#94E61D{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      amethyst: "&f%img_amethyst% &#AC74C4{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
      ruby: "&f%img_ruby% &#881856{nickname}%luckperms_suffix% %design_clr_money%%coinsengine_balance_short_money%  %design_clr_sapphire%%coinsengine_balance_short_sapphires%   &#D6CC90%statistic_player_kills% &f"
  death-coords:
    enable: true
    radius: 500
    price: 50
    time_in_ticks: 1200
    command: 'sapp take %player_name% 50 -s'
    not_found:
      enable: true
      text:
        - ' '
        - '%design_clr_primary%  Не было найдено подходящей локации за 20 попыток.'
        - '%design_clr_text_primary%  Вы можете попробовать еще раз. %design_clr_primary%/backrtp'
        - ' '
    success:
      enable: true
      text:
        - ' '
        - '%design_clr_primary%  Телепорт на координаты %design_clr_text_primary%%x% %y% %z%'
        - ' '
    deny:
      enable: true
      text:
        - ' '
        - '%design_clr_primary%  Вам не хватает %diff% сапфиров'
        - ' '
    message:
      enable: true
      text:
        - ' '
        - '%design_clr_primary%  Координаты смерти %design_clr_text_primary%%x% %y% %z%'
        - ' '
  sound: #/sutil rSound world 10 5 5 5 sound 0.2 2 #играет звук в радиусе #rSound <world> <x y z> <r> <sound> <volume> <pitch>
    enable: true
  randomizer:
    enable: true
    randomtasks:
      pickRandomSkin:
        skin1:
          chance: 30
          commands:
            - 'lp user %player_name% permission set itemskins.sword.calamity'
            - 'sutil sendmessage %player_name% '
            - 'sutil sendmessage %player_name% %design_clr_primary%  Вы получили скин %design_clr_text_primary%фиолетовый разрушитель'
            - 'sutil sendmessage %player_name% %design_clr_primary%  Применимо к %design_clr_text_primary%незеритовый меч'
            - 'sutil sendmessage %player_name% '
            - 'itemskin preview %player_name% netherite_sword calamity'
            - 'sutil playsound %player_name% UI_TOAST_CHALLENGE_COMPLETE 0.2 2'
        skin2:
          chance: 30
          commands:
            - 'lp user %player_name% permission set itemskins.sword.justice'
            - 'sutil sendmessage %player_name% '
            - 'sutil sendmessage %player_name% %design_clr_primary%  Вы получили скин %design_clr_text_primary%меч легионера'
            - 'sutil sendmessage %player_name% %design_clr_primary%  Применимо к %design_clr_text_primary%незеритовый меч'
            - 'sutil sendmessage %player_name% '
            - 'itemskin preview %player_name% netherite_sword justice'
            - 'sutil playsound %player_name% UI_TOAST_CHALLENGE_COMPLETE 0.2 2'
        skin3:
          chance: 30
          commands:
            - 'lp user %player_name% permission set itemskins.sword.titanium_blade'
            - 'sutil sendmessage %player_name% '
            - 'sutil sendmessage %player_name% %design_clr_primary%  Вы получили скин %design_clr_text_primary%титановый клинок'
            - 'sutil sendmessage %player_name% %design_clr_primary%  Применимо к %design_clr_text_primary%незеритовый меч'
            - 'sutil sendmessage %player_name% '
            - 'itemskin preview %player_name% netherite_sword titanium_blade'
            - 'sutil playsound %player_name% UI_TOAST_CHALLENGE_COMPLETE 0.2 2'
        skin4:
          chance: 30
          commands:
            - 'lp user %player_name% permission set itemskins.sword.silverlight'
            - 'sutil sendmessage %player_name% '
            - 'sutil sendmessage %player_name% %design_clr_primary%  Вы получили скин %design_clr_text_primary%лунный клинок'
            - 'sutil sendmessage %player_name% %design_clr_primary%  Применимо к %design_clr_text_primary%незеритовый меч'
            - 'sutil sendmessage %player_name% '
            - 'itemskin preview %player_name% netherite_sword silverlight'
            - 'sutil playsound %player_name% UI_TOAST_CHALLENGE_COMPLETE 0.2 2'
      playRandomSound: #todo or for removal
        sound1:
          chance: 30
          commands:
            - 'playsound'
            - 'sendmessage[penis]'
        sound2:
          chance: 30
          commands:
            - 'playsound'
            - 'sendmessage[penis]'



